### PR TITLE
RequestID in response Headers

### PR DESCRIPTION
**Pull request by kuldeeprishi**

### CODE REVIEW

**Comment by halfdan** [comment]
LGTM 💚

**Comment by sque** [comment]
@kuldeeprishi @halfdan Can you please open an issue and add a small use case how can this feature help?
And I will review it as soon as possible :)

**Comment by kuldeeprishi** [comment]
Basically my purpose was to return the Request-ID in response. 
This will be useful while integrating with frontend where in i can get the request id from the response (be it 400 or 500) and then trace the request in logs. For a distributed system it will be more beneficial.  Although i am currently achieving this by following in my flask application

```python
@app.after_request
def append_request_id(response):
    response.headers.add('X-REQUEST-ID', current_request_id())
    return response
```

**Comment by sque** [comment]
Thanks! I understand the cases but I feel there is no need to have this on by default. It can be either switched on through configuration, or instead of providing an implementation inside the code we could just add a small section in documentation with a guideline code for implementing this.

I only propose the later because it is really very trivial to implement it and can give more flexibility to end-developers to customize this behaviour according to their needs.

**Comment by kuldeeprishi** [comment]
Sure :)

**Comment by sque** [comment]
Cool!
Would you like to change your PR and add the equivalent section in documentation? Or would you like me to do it?

**Comment by kuldeeprishi** [comment]
Updated :)

**Pull request merged**
